### ISSUE TITLE
mutual  information

### ISSUE THREAD

**Issue by rawiasammout** [PhilChodrow/philchodrow.github.io#1]
Please could you give me a link of this contribution https://rdrr.io/github/PhilChodrow/compositional-complexity/

**Comment by PhilChodrow** [comment]
@rawiasammout Sorry, I'm not sure I understand your request. The repository for the compx package is  here: https://github.com/PhilChodrow/compx. Is that what you're looking for?

**Comment by rawiasammout** [comment]
Thanks for you reply in fact this is what i a looking for but Do u have any documentaion of your proposed package ??

**Comment by PhilChodrow** [comment]
The existing documentation is in the package itself, although it is admittedly incomplete. If you are using the code and have any questions, feel free to ask here.
